### ISSUE TITLE
Change ChemReg default display number for items in a project

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#597] opened 2015-10-30 16:46 UTC
• Default table view for inv projects should be 50 per page

**Comment by PaulBarrett79** [comment] 2015-11-03 16:11
Since the lists of compounds are only now through the search page, I have adjusted code so that if all of the selected projects are inventory only, then 50 items will be shown by default. If there are ANY chem projects selected, the default is kept at 10.

Pushed to github, awaiting deployment to staging/tagnew

**Comment by KarenPorter** [comment] 2015-11-11 10:04
Probably my misunderstanding - I search for 'colon' in assayreg and get 39 results - all from JW Project Example (inv - contains no structures), shown 10 per page.  Is this expected behaviour?

**Comment by PaulBarrett79** [comment] 2015-11-11 11:00
Hmm, reproducible.

Investigating.

**Comment by PaulBarrett79** [comment] 2015-11-11 11:58
In specifying the number of pages per project, instead of using the item from the model used to power the select list, I was using a new json object with the page information in. Changing the reference to the actual select box model position fixes this.

If all of the selected projects are inventory only, then 50 items will be shown by default. If there are ANY chem projects selected, the default is kept at 10.

**Comment by PaulBarrett79** [comment] 2015-11-11 12:03
Pushing to github

**Comment by PaulBarrett79** [comment] 2015-11-11 15:40
How annoying, this needs a fix for AssayReg and a separate fix for ChemReg.

**Comment by PaulBarrett79** [comment] 2015-11-11 16:04
Fix for both - awaiting deployment to staging/sandbox (chemreg) and staging/tagnew (assayreg)

**Comment by PaulBarrett79** [comment] 2015-11-11 16:16
Deployed to staging/sandbox (chemreg)

Awaiting next assayreg deployment.

**Comment by PaulBarrett79** [comment] 2015-11-11 16:18
Since this as specified as a ChemReg fix, marking as ready for testing

**Comment by KarenPorter** [comment] 2015-11-12 11:01
All of the projects in tagnew are assay type so I can't test this fully at the moment to get a result of 10 (but Paul and I think there's still an issues here in any case).

Alternative suggestion @aekhendry - in all search results (regardless of project types searched) we make the default results 50, and have the other options as 20 and 100.

**Comment by KarenPorter** [comment] 2015-11-27 09:05
This is still in Code Review list despite being labelled for Sprint 1 of November.  Can you please determine if still an issue or resolved and update appropriately @aekhendry

**Comment by PaulBarrett79** [comment] 2015-11-27 13:15
This has been changed to 50 per page with options for 10, 20, 50 and 100.

Deployed to staging/chembiohub

**Comment by KarenPorter** [comment] 2015-11-27 15:16
chemreg does default to 50.  see http://staging.chembiohub.ox.ac.uk/chembiohub/#/search?archived=false&project__project_key__in=chembl-project where I'm testing but the table of results itself seems to have regressed.  Now have a bunch of white space below results again (which we've had before but i'm pretty sure was fixed)

**Comment by strets123** [comment] 2015-12-01 11:00
Issue captured elaswhere in the handsontable reinstall issue

**Closed** 2015-12-01 11:00 UTC
Labels: enhancement, Proposed for November
