### ISSUE TITLE
The search my compounds interface breaks after change of parameters

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#833] opened 2016-02-01 15:23 UTC
Given I search for my compounds in a project
When I click another parameter keeping my name in place
Then it comes back with zero results

This is due to an error in the way the user URI in the url is serialized

**Comment by PaulBarrett79** [comment] 2016-02-26 09:17
possible duplicate of #712

**Comment by KarenPorter** [comment] 2016-02-26 12:07
#712 is different - I can reproduce for anyone interested.

However, I can't reproduce #833 in hubtest.  Is this still an issue?

**Comment by KarenPorter** [comment] 2016-02-26 13:19
fixed

**Closed** 2016-02-26 13:19 UTC
Labels: bug, ChemiRegV2, Search flexibility
