### ISSUE TITLE
Searching for an incorrect structure I get a message 'Loading selected items failed' message.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#712] opened 2015-11-24 08:58 UTC
Searching for an incorrect structure I get a message 'Loading selected items failed' message.

**Comment by aekhendry** [comment] 2015-11-30 16:12
Can you define incorrect? I'm not sure how to replicate this. Also what project you were searching in please.

**Comment by KarenPorter** [comment] 2016-02-01 14:45
@aekhendry In search structure - just draw any nonsense structure and hit 'run structure search'.  not related to any project.  It's about how invalid structures are handled.

**Comment by aekhendry** [comment] 2016-02-01 17:06
Yes tested this and is still a bug. hubtest chrome

**Comment by PaulBarrett79** [comment] 2016-02-26 09:17
Possible dupe of #833

**Comment by KarenPorter** [comment] 2016-05-09 09:52
Resolved by refactoring.

**Closed** 2016-05-09 09:52 UTC
Labels: app: ChemReg, bug, ChemiRegV2, name: Karen, priority: Medium
