### ISSUE TITLE
Top menu can be made to re-appear so you get a double menu when using firefox

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#394] opened 2015-07-02 13:21 UTC
It happens on top of the table view

**Comment by KarenPorter** [comment] 2015-07-09 11:28
Can't reproduce so closing.

**Comment by KarenPorter** [comment] 2015-07-09 11:29
was something specifically done to resolve this?

**Comment by strets123** [comment] 2015-07-09 13:42
Yes the original menu now has a height of 0 so you dont see it but it still performs its function in making the widths calculate properly

**Comment by aekhendry** [comment] 2015-07-13 09:58
I can't reproduce so I'm considering this fixed

**Closed** 2015-10-30 15:09 UTC
Labels: redfor1.0
