### ISSUE TITLE
[" item here "] formatting being exported in excel

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#433] opened 2015-07-15 10:04 UTC
["Customisable plate layouts", "qPCR", "Luciferase assay", "ELISA assay"]
This is the current format tag and create fields are exporting in excel. This needs to be plain text seperated by a comma. If anyone wants to use this data in a subsequent excel sheet they will have to do a fair amount of processing.

**Comment by PaulBarrett79** [comment] 2015-07-22 12:45
Duplicate of #178

**Closed** 2015-07-22 12:46 UTC
Labels: duplicate, enhancement, File Export
