### ISSUE TITLE
The table view is inconsistent in the height it presents on loading

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#326] opened 2015-06-04 08:57 UTC
The table view is inconsistent in the height it presents on loading. this is in all examples where you can see a table. For example, sometimes it loads and the table is tall enough to view 3 compounds, othertimes I cannot even make out one.
Tested on Hub, chrome.
I'm pretty sure this is a duplicate but i can't find the original

**Comment by PaulBarrett79** [comment] 2015-06-04 13:09
Duplicate of #278

**Closed** 2015-06-04 13:10 UTC
Labels: bug, Compound representation, duplicate, IsoTab
