### ISSUE TITLE
Refactor project data fields front end

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#907] opened 2016-02-15 20:36 UTC
Make the search front end of project data fields more of a standard advanced search like on PubChem

**Comment by strets123** [comment] 2016-02-15 20:38
Allow search by ranges and make the interface more flexible, links to #906 #868 #867

**Comment by strets123** [comment] 2016-02-15 20:39
This task is a 1 week sprint candidate

**Comment by PaulBarrett79** [comment] 2016-02-24 10:44
This would be as per the document at S:\OxChemBioDB\Project Documents\UI Mockups\chemireg-new-search.pdf containing the wireframes for this functionality

**Comment by PaulBarrett79** [comment] 2016-02-25 10:52
[chemireg-new-search.pdf](https://github.com/thesgc/chembiohub_helpdesk/files/146357/chemireg-new-search.pdf)

**Comment by strets123** [comment] 2016-03-01 13:31
For the search of patterns then we need 

1) Chemical synonyms
2) Pattern replacement based on special characters e.g.

([^A-Za-z0-9\s\t\n])+

is a pattern that is replaced using the

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern-replace-charfilter.html

We can also generate a chemical search analyzer using synonyms for functional groups

**Comment by strets123** [comment] 2016-03-01 13:31
http://pubs.acs.org/doi/suppl/10.1021/ed2002994

**Comment by strets123** [comment] 2016-03-01 13:39
dos2unix chems.txt

**Comment by strets123** [comment] 2016-03-09 10:40
Test cases

Given I click a column header button
Then I see a fieldset above with hide, sort and filter options
And the top of the column is highlighted in blue

When I click hide column and close, the table reloads, the column goes away and the hide can be cancelled either by clicking the name of the field in hidden fields and clicking show column or by clicking the close button in the hidden fields area


Given I have selected a column
When I click 1-000..a-z sort then the sort appears in the sorts area with an appropriate icon
I cna remove the sort either by clicking on the no sort button or by clicking close in the sorts area


Given I have selected a column
When I click close in the column options area top right 
then the options are disapears and the top[ of the column unhighlights

Given I have selected a column
When I change the query type
All previous queries for that column are removed

Given I have selected a column
When I change the query type to blank or non blank
The filter automatically applies
For other query types the filter only applies when I change the form

Where more than one input is required then the other required field is validated as you type

If you delete the contents of the keyword you are searching for, again the field is marked as required and the filter removed until you have added a valid word as the filter


Phrase queries...

Given I search in a field that has (myword) in it I can search either for

(m

or for

m

Both will return the correct value

**Comment by KarenPorter** [comment] 2016-03-11 14:40
2 things:

"When i click 1-000..az sort" .   Clicking on either sort order buttons, I get - Sorry, there was an error with that query. No data found. msg

i think this is still to be implemented, but can't pass this card until the behaviour is as expected.

and phrase queries testing - 

looks good with existing data but what about when I add new data via projects page?  should that be accessible to these results?

I added a value to 4 records in the Adam shouldnt have this project, field 'ad'.  

the values were:
 Mmmm
( mmm)
Nnnn
mm

then i search for 'mm' and get no results

**Comment by PaulBarrett79** [comment] 2016-04-19 10:40
My best guess is that there is some form of indexing issue here with the values not being found, and an incorrect URL construction for the sort.

Marked as for Andy's attention to estimate.

**Comment by strets123** [comment] 2016-04-20 08:50
Sorting issue - fields with some blank rows do not sort properly, 2 hour to fix

**Comment by strets123** [comment] 2016-04-22 08:56
The sorting issue is fixed but investigating the "search for things with symbols" issue a bit more there seems to be a problem with the encoding code that is "supposed" to stop  issues with backend communication.

I am going to raise a neew issue as this affects cunieform signs but not parantheses

**Comment by KarenPorter** [comment] 2016-04-25 07:50
No search results showing in results page.  

I ran a search for Simple Chemical Example and the results showed '46 results', but the results table was empty.  I exported results and they were all in the export file.  

I reran the same query and got 26 results, which showed in the table and in the export file.  

I reran the same query and got 46 results, which showed in the table and the export file.  

Clearly we cannot afford to have any lack of confidence in search results.

**Comment by strets123** [comment] 2016-04-25 07:53
One cause of the issue with search results not showing was some problems with the handsontable editor code which have now mostly been addressed. We need to file a pull request to completely fix error handling here on the handsontable side, but for our current purposes it should be fixed. This includes the issue when you add a new field and then existing data does not show up.

**Comment by KarenPorter** [comment] 2016-04-25 11:03
can't reproduce last recorded error so assume fixed.

**Closed** 2016-04-25 11:03 UTC
Labels: ChemiRegV2, for Andy review, Search flexibility
