### ISSUE TITLE
Bug with structure search and project

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#668] opened 2015-11-11 17:18 UTC
cc @aekhendry this is now fixed

**Comment by KarenPorter** [comment] 2015-11-12 10:32
Please ensure we have no issues in the system like this - with no clue as to what the bug is, how it is manifested and what the newly expected behaviour is.  I have no means of testing.

**Comment by strets123** [comment] 2015-11-12 10:42
Apologies, we had just discussed this verbally and I was rushing for the train and thought it better logged than not logged.

The issue was that the structure search threw a 400 error if used together with project or created by.

It was fixed

**Comment by KarenPorter** [comment] 2015-11-12 11:17
thanks.  Tested. I've raised a new issue since I noticed in testing that the created by list shows name plus SSOid.  other than that it passes, so moving to awaiting deployment.

**Closed** 2015-11-14 09:22 UTC
