### ISSUE TITLE
I did a 'thing' where i got the search on the project list page to not drop down as I typed.  

I th

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#721] opened 2015-11-27 14:46 UTC
I did a 'thing' where i got the search on the project list page to not drop down as I typed.  

I think it is - type in search box (see drop down filtering nicely), navigate away to another tab, navigate back - backspace what you have in there and type text - no drop down.

**Comment by KarenPorter** [comment] 2016-02-01 14:41
closing - I can't reproduce.

**Closed** 2016-02-01 14:41 UTC
Labels: app: AssayReg, bug, For Andy and Paul Review, name: Karen, priority: Low, status: New
