### ISSUE TITLE
supplementary data fields do not work on chemireg draw a compound

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#827] opened 2016-01-29 19:06 UTC
Currently submitting a list needs to be converted to an object in order to submit

**Comment by KarenPorter** [comment] 2016-02-01 11:13
could you please expand @strets123?  I don't understand what this issue is.

**Comment by KarenPorter** [comment] 2016-05-09 11:18
tested - supplementary data added and visible in modal window (can't search or see in results table but that is by design).  Closing

**Closed** 2016-05-09 11:18 UTC
