### ISSUE TITLE
Referencing registered compound doesn't provide sufficient functionality.  

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#578] opened 2015-10-28 08:43 UTC
Referencing registered compound doesn't provide sufficient functionality.  How much effort would it take to allow a drop down of ids (preferably with image) when you add a single activity?

**Comment by PaulBarrett79** [comment] 2015-11-02 15:56
Duplicate of #585

**Closed by PaulBarrett79** 2015-11-02 15:56 UTC
Labels: app: AssayReg, enhancement, name: Karen, priority: Low, Proposed for November, status: New
