### ISSUE TITLE
Can't clear out the custom field values in the search.  

It looks like I've deleted the 2 tagged cu

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#306] opened 2015-06-03 10:18 UTC
Can't clear out the custom field values in the search.  

It looks like I've deleted the 2 tagged custom fields in my search, but the search isn't rerun and the URL isn't updated.  If I change the functional group search that seems to be taken into account, but not custom fields.

**Comment by PaulBarrett79** [comment] 2015-06-10 09:45
Pressing cancel also does not clear the custom field search parameters

**Comment by PaulBarrett79** [comment] 2015-06-10 10:44
Custom field selections not being cleared from the new url parameters before new search is performed. They're not in the form but the URL parameters aren't being changed.

**Comment by PaulBarrett79** [comment] 2015-06-10 10:49
Deleting a custom field from the list is not being reflected in the searchform.

**Comment by PaulBarrett79** [comment] 2015-06-10 11:17
Custom field now uses the fields in the form correctly. Removing a custom field should now apply the correct search.

Pushed to github

**Comment by PaulBarrett79** [comment] 2015-06-10 14:05
Deployed to staging/sandbox, verified fix has been deployed

**Comment by KarenPorter** [comment] 2015-06-10 15:30
Discuss :)

What do we think Cancel should do?  I added some custom field filters, ran that search, then clicked cancel - it applies the same filter.  Is that by design and if so, what's the expected behaviour?

**Comment by PaulBarrett79** [comment] 2015-06-10 15:37
No cancel should clear the search of all selected parameters and return the form to it's original state.

If we want the behaviour to be reset the form ONLY, while retaining the search results for that  search and not reloading the page, we should reword the button to "Clear"

**Comment by KarenPorter** [comment] 2015-06-10 15:52
Raised an issue to address the Cancel button functionality.

**Comment by KarenPorter** [comment] 2015-06-10 15:52
defect as originally reported here - tested and signed off.

**Closed** 2015-10-30 15:15 UTC
Labels: app: ChemReg, bug, name: Karen, priority: Medium, status: New
