### ISSUE TITLE
The ability to sort projects in project view will be necessary soon

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#502] opened 2015-08-17 09:28 UTC
It would be great to be able to sort projects in project view i.e. alphabetically or by date last edited. As groups gather more projects this will almost certainly become a requested enhancement soon

**Comment by strets123** [comment] 2015-10-30 15:32
Let's add a simple search bar

**Comment by PaulBarrett79** [comment] 2015-11-02 16:14
Duplicate of #596

**Closed by PaulBarrett79** 2015-11-02 16:14 UTC
Labels: enhancement, Project Level, Proposed for November
