### ISSUE TITLE
Scarab integration refactoring

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#460] opened 2015-07-24 07:39 UTC
In order to allow plugins for assay reg and for the scarab integration a lightweight plugin framework will be developed. This will also help the code remain more decoupled and stop the ongoing pollution of current frontend components.

This work will consist of a few parts, 

* The headers of the table view need to be defined as one JSON file with enough information to cover
     * Handontable config
     * Filters config
     * Sorts config
     * Plugins config (potentially including "map")
* Actions should be strings that are turned into functions by dependency injection
* An event workflow should be available to reload the data after a change to the columns config
* Plugins would be configured in the project configuration, a plugin would be a celery task or an API call that is called by celery. Therefore plugins will require each of these features:
     * They will run a task for each of the items uploaded 
     * A status to say if they have been run or not yet
     * Optionally you would specify what column is to be used for the function to  run e.g. to generate images you use the ctab
     * The plugin will instruct CBH what needs to be written to the object by sending back a JSON patch
     * The status flag will be set on that column once the plugin has run for a given  field
     * Initially the plugins will be run in one request cycle

**Comment by PaulBarrett79** [comment] 2015-11-02 15:40
Duplicate of #585

**Closed** 2015-11-02 15:40 UTC
Labels: enhancement
