### ISSUE TITLE
Failing to process a file - no errors

I have a file I've uploaded to Wood Group 2.0 several times t

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#312] opened 2015-06-03 14:21 UTC
Failing to process a file - no errors

I have a file I've uploaded to Wood Group 2.0 several times that now doesn't process as cleanly as once it did.

This may be covered in existing issues but I'm raising separately because the behaviour seems to have changed recently. 

1. If I don't do any mapping it fails (progress for 1-2 secs then nothing)
2. If I automap - none of the fields actually map, despite looking to me like they have the right field names.
3.  if I map the fields manually - same as 1 above
4.  If I double-click - it processes the file (but creates double the number of records).

**Comment by PaulBarrett79** [comment] 2015-06-22 15:40
Mapping using drag/drop has now been removed from the application - this needs revalidating that it is still an issue

staging/sandbox

**Comment by KarenPorter** [comment] 2015-06-29 07:20
Can't reproduce - approach to loading is now refactored. Closing.

**Closed** 2015-10-30 15:14 UTC
Labels: app: ChemReg, bug, name: Karen, priority: High, status: New
