### ISSUE TITLE
List view font and position inconsistencies.

Some fields top-aligned, others centre-aligned.  Diffe

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#304] opened 2015-06-03 08:27 UTC
List view font and position inconsistencies.

Some fields top-aligned, others centre-aligned.  Different font for Id compared to other fields.  Are they different colours too?

**Comment by PaulBarrett79** [comment] 2015-06-10 13:57
Centre-aligning was not being applied to custom fields correctly - now fixed.

The light grey font is supposed to indicate that it is a read only field. It is up for debate about whether we should override this and make everything the same font colour.

**Comment by PaulBarrett79** [comment] 2015-06-10 13:57
Pushed to github

**Comment by PaulBarrett79** [comment] 2015-06-10 14:06
Deployed to staging/sandbox, verified fix has been deployed

**Comment by KarenPorter** [comment] 2015-06-10 14:45
I can see fix applied and row is now consistently aligned (centre and middle)

1. ID font is serif and all others are sans-serif

2. Looking at list for marsden project where there are a lot of synonyms. The column is so wide, and the entries being centre aligned vertically means that when I look at the results, this column looks empty.  I can scroll right to see the values but would this be instinctive?  Maybe columns should be limited to a max width?  maybe if greater than a certain width that column should be left aligned?  Not sure what the optimum behaviour should be.

**Comment by PaulBarrett79** [comment] 2015-06-10 14:55
ID font is serif by design - it is a monspaced font to stop IDs wrapping onto two lines

**Comment by PaulBarrett79** [comment] 2015-06-10 14:55
*monospaced

**Comment by KarenPorter** [comment] 2015-06-10 15:43
Does that mean there isn't an acceptable monospaced sans-serif font option?

**Comment by PaulBarrett79** [comment] 2015-06-11 10:40
I have changed the font to one which will be acceptable across OSes and browsers. I've done it through the chembiohub-theme repository so it will be available to all our apps. Pushed to github.

**Comment by PaulBarrett79** [comment] 2015-06-11 10:40
Deployed to sandbox/staging

**Comment by PaulBarrett79** [comment] 2015-06-11 14:00
The large cells question - you would have to sacrifice layout consistency to make these more readable. 

Max width does not make sense if you can already scroll the table L-R - you make the data less readable by limiting width.

The only solution left is left-align certain cells - do we do this with all custom field text-based cells?

**Comment by KarenPorter** [comment] 2015-06-11 15:09
Yep – I’d say do that.

We may develop future functionality where the person defining the fields indicates l- or c- alignment but for now I think a default left align would be better than what we have.

**Comment by PaulBarrett79** [comment] 2015-06-15 10:09
Custom fields in the table are now left-aligned. Pushed to github

**Comment by PaulBarrett79** [comment] 2015-06-16 14:25
Deployed to staging/sandbox

**Comment by KarenPorter** [comment] 2015-06-18 10:04
passed testing.

**Closed** 2015-10-30 15:15 UTC
Labels: app: ChemReg, name: Karen, priority: Low, status: New
