### ISSUE TITLE
Can't edit uncurated fields

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#325] opened 2015-06-04 08:15 UTC
There may be a reason for this, but the user wont know it and so it needs to be clear why this is. They will just want to be able to edit their data.

**Comment by nroam** [comment] 2015-06-04 08:16
See #321 - do we need grey backgrounds to signify that a field is uneditable?

**Comment by PaulBarrett79** [comment] 2015-06-04 14:07
Yes I'm going to mark this as a duplicate of #321 - same root issue.

**Closed** 2015-06-05 12:42 UTC
Labels: Custom Fields, duplicate, enhancement
