### ISSUE TITLE
No indication as to why a specific row in my input file hasn't been processed.

I have a file with 1c1n+[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
c1ncc2n(c1CCO)c(nn2)c1ccc(cc1)OC(F)F
C1NCc2n(C1CCO)c(nn2)c1ccc(cc1)OC(F)F
c1n+[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
c1n+[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
CCC
CCCCC

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#385] opened 2015-06-26 14:06 UTC
No indication as to why a specific row in my input file hasn't been processed.

I have a file with 10 rows - one of which has an invalid structure.  I upload file - that row was missed out in table (so 10 uploaded records / 9 results).  I corrected SMILES and got 10 uploaded recs / 10 results.  I then broke molecule again and got 10 /10 but the results included a duplicate of the record before my broken one, and not my invalid record.

Correct SMILES are -
c1[n+](cc2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
c1ncc2n(c1CCO)c(nn2)c1ccc(cc1)OC(F)F
C1NCc2n(C1CCO)c(nn2)c1ccc(cc1)OC(F)F
c1[n+](cc2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
c1[n+](cc2n(c1OCCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
CCC
CCCCC

Invalid SMILES are:
c1[n+](cc2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
c1ncc2n(c1CCO)c(nn2)c1ccc(cc1)OC(F)F
C1NCc2n(C1CCO)c(nn2)c1ccc(cc1)OC(F)F
c1[n+](cc2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)Cl
c1[n+](cc2n(c1OCCCc1cc(c(cc1)F)F)c(nn2)c1ccc(cc1)OC(F)F)[O-]
c1nc(c2n(c1OCCc1cc(c(cc1)F)F)c(nn2)c1cccc(cc1)OC(F)F)Cl
CCC
CCCCC

**Comment by KarenPorter** [comment] 2015-06-26 14:38
Also, this does a weird thing to the duplicates filter - i get the record before the broken one, on it's own (so what is that a duplicate of?).

This is probably easier to demo than to write up coherently.

**Comment by strets123** [comment] 2015-07-02 11:19
linked to the smiles one

**Comment by strets123** [comment] 2015-07-07 14:20
I have now added an info column. This will provide the SMILES if the SMILES could not be processed for that record. It also provides info if this is a duplicated record etc.

**Comment by strets123** [comment] 2015-07-09 09:33
Now added a readonly to fields where it is ignored due to error

**Comment by strets123** [comment] 2015-07-09 15:55
Also added a total for the number to be ignored that updates dynamically

**Comment by KarenPorter** [comment] 2015-07-13 12:58
I attempted to add these 10 records in an Excel file with only SMILES in the file and a header value that can't be automapped.

When i upload the file with the 10 records, they are shown in the table of structures (no structure and no info).  I then map my header to SMILES for chemical structure value and now get 'File cannot be processed.....' message.

If i paste these 10 SMILES into the 'paste.... here' box, they are each interpreted correctly - so with relevant structure, info and action (ignore 3, create new batch for 7).

**Comment by strets123** [comment] 2015-07-21 10:10
Should now be fixed

**Comment by KarenPorter** [comment] 2015-07-23 09:34
passed testing.

**Closed** 2015-10-30 15:08 UTC
Labels: app: ChemReg, name: Karen, priority: High, redfor1.0, status: New
