### ISSUE TITLE
Exported an xls from a set of results with 0 records - 1000 records were downloaded.  Project was Ch

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#772] opened 2015-12-14 14:35 UTC
Exported an xls from a set of results with 0 records - 1000 records were downloaded.  Project was ChemReg Playground, on Hub

**Comment by KarenPorter** [comment] 2016-02-01 13:51
Can't reproduce because of existing no exception error - review along with that issue

**Comment by KarenPorter** [comment] 2016-02-01 13:52
Should the 3 issues 789, 818 and 821 be addressed together?  and 772

**Comment by KarenPorter** [comment] 2016-05-09 10:20
Resolved.  Closing

**Closed** 2016-05-09 10:20 UTC
Labels: app: ChemReg, bug, File Export, name: Karen, priority: Medium, status: New
