### ISSUE TITLE
Have a workflow for unpinning a custom field

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#263] opened 2015-05-28 15:24 UTC

**Comment by strets123** [comment] 2015-05-28 15:27
Currently it may appear that custom fields are not visible when you have searched for them but this has not been designed in to the system. You just have to keep all the fields there for now, perhaps we could do a hide feature but we haven't up to now

**Comment by aekhendry** [comment] 2015-05-29 09:22
I'm not sure i fully understand what the issue is here, could whoever registered it please give a working example?

**Comment by KarenPorter** [comment] 2016-02-01 14:22
@aekhendry why isn't this updated or labelled for A&P to comment if that's what is needed?

**Comment by aekhendry** [comment] 2016-02-01 17:25
Closing as no longer relevant

**Closed by aekhendry** 2016-02-01 17:25 UTC
Labels: Custom Fields, enhancement, for Adam review, Search
