### ISSUE TITLE
Unprocessable compound should not be able to be saved. - attempting to causes error

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#553] opened 2015-10-02 12:29 UTC
I submit one compound for file upload (SDF). In preview file uploads but compound is displayed in table as ‘data not processable’. If I click save I get infinite loading screen. If I submit same compound alongside one in which data is processable and click save, then working compound is saved, unprocessable one is ignored as expected. We need to stop users from being able to save if none of the present data is processable.

**Comment by PaulBarrett79** [comment] 2015-11-02 16:07
Duplicate of 618

**Comment by PaulBarrett79** [comment] 2015-11-02 16:07
#618

**Closed** 2015-11-02 16:07 UTC
Labels: bug, File Upload, Proposed for November
