### ISSUE TITLE
Platemap data type for assayreg

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#806] opened 2016-01-13 09:14 UTC
Simple approach - 1 day
-----------------
Small changes to AssayReg would make it suitable for registering and visualising plate maps in the standard data overview view
It might be possible to have a "compound platemap" or a "numeric platemap"
The platemaps could be viewed in the current data overview page as in 12 rows per "assay" in the current data grid.

More complex approach - 3 days
---------------------------
Alternatively platemaps could be added as rich text by extending the ckeditor table plugin

http://docs.ckeditor.com/#!/guide/dev_table

**Comment by strets123** [comment] 2016-01-22 08:27
This requirement leads nicely into pivot tables - the interrface should be built in such a way it can be used for pivotting.

We can add a controller factory to the assayreg search page

**Comment by KarenPorter** [comment] 2016-02-01 11:38
And if it were to be delivered via Chemireg rather than AssayReg (per proposal to incorporate the later functionality into the former) ? @strets123

**Comment by PaulBarrett79** [comment] 2016-02-03 11:23
I am meeting with Katherine England to discuss requirements and analyse existing process 4th Feb.

**Comment by PaulBarrett79** [comment] 2016-02-04 16:23
Met with Katherine today and my findings are on the S drive s:\OxChemBioDB\Project Documents\Requirements Capturing\ChemiReg\KEngland-user-requirements.docx

**Comment by KarenPorter** [comment] 2016-02-18 09:27
@PaulBarrett79 please update with progress to date.

**Comment by PaulBarrett79** [comment] 2016-02-24 10:38
This is being held up at the moment by a bug in the angular-schema-form-ui-select library which we are using to look up the UOX IDs. I need to try and fix this or find an alternative way to provide a typeahead field for assigning a UOX ID to a well. At the moment the user can assign the well and the information is retained, but it does not display the compound ID when returning to the well.

The functionality also requires some work on display for smaller resolution screens. I then need to meet with Kathryn England to ensure that the functionality meets expectations while it is still at an early stage.

**Comment by PaulBarrett79** [comment] 2016-03-08 13:40
This is now awaiting deployment to hubtest

**Comment by PaulBarrett79** [comment] 2016-04-04 13:46
Work was required on this piece of functionality to change:
Plates should now be plate-per-batch rather than plate-per-project;
The UOX ID lookup needed to be converted to use the new pick from list widget rather than uiselect;
To save, retrieve and edit plates we had to change to use the CBHCompoundBatch APIs rather than the plate specific ones we set up;
Each plate should be part of a given project, affecting the route in the application;
Pagination was required on the list of plates and that this required use of the new search APIs.

Plate Map type projects can now be configured from the Add Project menu.
Links will be available to take the user to the add and list pages as appropriate.

Pushed to github

**Comment by PaulBarrett79** [comment] 2016-04-18 10:55
This is now available for testing on hubtest

**Comment by aekhendry** [comment] 2016-04-18 15:26
Tested on demo. I'm finding multiple bugs and inconsistencies. 

1. trying to create a 48 well plate breaks it - the plate is not rendered when clicking save. Requires refresh to  restart.
2. If I click save before all necessary options are selected in plate set up it breaks. The plate is not rendered correctly and only way back is through page refresh. 
3. I create a 96 well plate and add some things. i click save. It takes me to the next page but no plate is displayed. It does not appears to be saving correctly.

**Comment by PaulBarrett79** [comment] 2016-04-19 10:32
Point 1 - unknown problem with setting up that plate dimension -my initial guess is it  could be to do with the fact we've changed where the form comes from.

Point 2 - validation being bypassed

Point 3 is related to the paging of the list of plates - it is saving correctly but the list isn't being retrieved because the start page is determined to be "NaN"

**Comment by PaulBarrett79** [comment] 2016-04-19 10:33
Because there are multiple issues or this, and because it is not urgently required functionality, it could be "switched off" by hiding from the project choices until higher priority issues are dealt with. I estimate this is about 5 hours work.

**Comment by PaulBarrett79** [comment] 2016-04-20 15:17
1 - plate dimension - weird problem with not being able to parse the number of plate wells. Fixed - now renders a 4x6 grid for 48 well plate.
2 - validation is now enforced for the plate setup

**Comment by PaulBarrett79** [comment] 2016-04-20 15:27
point 3 - paging now fixed.

Pushing to github

**Comment by PaulBarrett79** [comment] 2016-04-21 08:56
Available for testing on staging/staging

**Comment by KarenPorter** [comment] 2016-04-21 10:49
Plate map entry on the list page has 'add plate' and 'list plate' options on LHS - both link to same URL

**Comment by KarenPorter** [comment] 2016-04-21 10:52
2 typos in message - 'Plate maps curently in the system. To add a plate map to thie project, click here'

**Comment by KarenPorter** [comment] 2016-04-21 10:54
When I click the edit icon on the list of plate maps - I get a grey box below the list of plates.  I can't interact with it and it doesn't go when I move from page to page.

**Comment by KarenPorter** [comment] 2016-04-21 10:56
When I attempt to add a plate - i get the warning message 'There are required fields missing data' but no indication as to which fields are required.

**Comment by KarenPorter** [comment] 2016-04-21 10:58
typo in error message - 'You must add a some details'

**Comment by KarenPorter** [comment] 2016-04-21 11:04
When I bring up a plate I've created to edit, it initially looks ok but when I click in a well, the detail capture fields disappear

**Comment by KarenPorter** [comment] 2016-04-21 11:05
When I've been editing a plate and I click on another, nothing happens

**Comment by KarenPorter** [comment] 2016-04-21 11:06
No validation of plate names- I can create duplicates

**Comment by KarenPorter** [comment] 2016-04-21 11:21
icons and text in the platemap project type on the project list page don't align with chem and inventory project type text.

**Comment by PaulBarrett79** [comment] 2016-04-21 14:10
"Plate map entry on the list page has 'add plate' and 'list plate' options on LHS - both link to same URL"

Corrected

**Comment by PaulBarrett79** [comment] 2016-04-21 14:12
"2 typos in message - 'Plate maps curently in the system. To add a plate map to thie project, click here'"

Corrected

**Comment by PaulBarrett79** [comment] 2016-04-21 14:44
"typo in error message - 'You must add a some details'"

Corrected

**Comment by PaulBarrett79** [comment] 2016-04-21 15:19
"When I've been editing a plate and I click on another, nothing happens"

Can't reproduce this even on staging. Plate is always refreshed.

**Comment by PaulBarrett79** [comment] 2016-04-21 15:23
"No validation of plate names- I can create duplicates"

It is a required field but does not check for duplicates. Should it? Duplicate name does not break the system - it's essentially a custom field value. Creation date is supplied in the list to differentiate plates if necessary.

**Comment by PaulBarrett79** [comment] 2016-04-21 15:26
"When I bring up a plate I've created to edit, it initially looks ok but when I click in a well, the detail capture fields disappear"

Took a while to work this out - if you switch between a 48 and 96 well plate it's not re-rendering with the new shape. So wells outside of the 6x8 grid "don't exist" and cause the form to disappear.

**Comment by PaulBarrett79** [comment] 2016-04-21 15:41
Moved the grid setup into a callable function so that it can be rerendered when the plate dimensions change. Can't test my theory until I can add a plate of a different dimension!

**Comment by PaulBarrett79** [comment] 2016-04-22 08:24
My theory works. Switching between 48 and 96 well plates now redraws the plate with the correct dimensions.

**Comment by PaulBarrett79** [comment] 2016-04-22 09:00
"icons and text in the platemap project type on the project list page don't align with chem and inventory project type text."

Icon alignment changed - all now align

**Comment by PaulBarrett79** [comment] 2016-04-22 09:02
Pushed to github, awaiting deployment on staging/demo

**Comment by strets123** [comment] 2016-04-25 07:47
@PaulBarrett79 The list plates table does not set the "pids" filter and so you see "plates" from all projects

**Comment by PaulBarrett79** [comment] 2016-04-25 08:30
Project filter was being added but needed to be changed to reflect the new search functionality. Now applied and pushed to github.

**Comment by KarenPorter** [comment] 2016-04-26 08:11
@strets123 can we get this into demo for testing please?

**Comment by KarenPorter** [comment] 2016-04-26 10:49
Plate map entry on the list page has 'add plate' and 'list plate' options on LHS - both link to same URL

Not addressed

**Comment by KarenPorter** [comment] 2016-04-26 10:51
Edit configuration for a platemap project brings up an empty config box so not relevant.

**Comment by KarenPorter** [comment] 2016-04-26 10:54
Editing user roles - save changes and close doesn't do anything.

**Comment by KarenPorter** [comment] 2016-04-26 11:01
When I attempt to add a plate - i get the warning message 'There are required fields missing data' but no indication as to which fields are required.

Not addressed

**Comment by KarenPorter** [comment] 2016-04-26 11:04
Save plate isn't working

**Comment by KarenPorter** [comment] 2016-04-26 11:12
Added data to a well, then saved plate - it saved the well info but didn't colour it green.

**Comment by KarenPorter** [comment] 2016-04-26 11:19
Question about spec- how is the pick from list populated?

**Comment by KarenPorter** [comment] 2016-04-26 11:25
The group would like to be able to use the ChemiReg search functionality to to find compounds present on a particular plate, and potentially all compounds on one row/column of a specified plate (for identifying controls, for example). They would also potentially like to be able to see a heatmap of where a compound is located within a plate – so they can load it up on the lab PC, see the physical location highlighted and retrieve with minimal fuss (not essential but we could provide for free).

notwithstanding the second part of this requirement (heatmap) - is it a minimum requirement to be able to retrieve a plate / well containing a specific compound?  I don't think that's possible.

**Comment by KarenPorter** [comment] 2016-04-26 11:37
Project data fields are defined as not required, but then when creating a new project I'm forced to add a value for them.

**Comment by KarenPorter** [comment] 2016-04-26 11:41
I can define any values for plate size - 48 and 96, but also 24, 3, six.  Only the first 2 can be interpreted and rendered as plates though.

**Comment by KarenPorter** [comment] 2016-04-26 11:44
If I define a plate size, and save that plate, then amend the size, it isn't re-rendered

**Comment by KarenPorter** [comment] 2016-04-26 11:49
When I'm editing a plate, there's nothing to indicate which plate I'm on.  Needs the name to be shown above the plate map

**Comment by KarenPorter** [comment] 2016-04-26 11:53
Added data to a well, then switched plates - it saved the well info but didn't colour it green.  Need to force a save well event and a save plate event before edit click event - or warn user they have unsaved data.

**Comment by PaulBarrett79** [comment] 2016-04-26 13:13
"Plate map entry on the list page has 'add plate' and 'list plate' options on LHS - both link to same URL"

LHS link removed

**Comment by PaulBarrett79** [comment] 2016-04-26 13:38
"When I attempt to add a plate - i get the warning message 'There are required fields missing data' but no indication as to which fields are required."

More verbose validation now added.

**Comment by PaulBarrett79** [comment] 2016-04-26 13:57
"When I'm editing a plate, there's nothing to indicate which plate I'm on.  Needs the name to be shown above the plate map"

Added

**Comment by PaulBarrett79** [comment] 2016-04-26 14:40
"Added data to a well, then saved plate - it saved the well info but didn't colour it green.  Need to force a save well event before saving plate - or warn user they have unsaved data."

Added a forced save of current well.

**Comment by PaulBarrett79** [comment] 2016-04-26 14:43
"Question about spec- how is the pick from list populated?"

Populated from compounds across projects that the logged in user has access to.

**Comment by PaulBarrett79** [comment] 2016-04-26 14:47
"notwithstanding the second part of this requirement (heatmap) - is it a minimum requirement to be able to retrieve a plate / well containing a specific compound?  I don't think that's possible."

It could be made possible because we are already using a modified version of the search interface to get the plate list. Could add a form which allows narrowing down of plates containing that cmpd.

**Comment by PaulBarrett79** [comment] 2016-04-26 15:07
"If I define a plate size, and save that plate, then amend the size, it isn't re-rendered"

I really can't see a situation where this would be wanted. If you've clicked the wrong size button - start again. Maybe the first form should be hidden when you click "Save plate" and that only clicking "Cancel" can get back to the first form?

**Comment by PaulBarrett79** [comment] 2016-04-26 15:10
"I can define any values for plate size - 48 and 96, but also 24, 3, six.  Only the first 2 can be interpreted and rendered as plates though."

Is anyone actually going to do this? A possibility is to make these choices uneditable.

**Comment by PaulBarrett79** [comment] 2016-04-27 10:50
The last two points I will create new cards for because they are distinct pieces of functionality to be tested.

**Comment by PaulBarrett79** [comment] 2016-04-27 11:05
Since this functionality is not urgently required for this release it should be signed off inconjunction with #1015 and #1016

**Comment by KarenPorter** [comment] 2016-05-10 09:05
@PaulBarrett79 can you please confirm this can now be closed as all comments either addressed or incorporated in other issues on te backlog?

**Comment by PaulBarrett79** [comment] 2016-05-20 16:24
All comments in here are now accounted for in other tickets for platemap functionality.

**Comment by KarenPorter** [comment] 2016-06-01 07:35
closing - requirements captured elsewhere

**Closed** 2016-06-01 07:36 UTC
Labels: enhancement, Platemap, status: Fixed - awaiting testing
