### ISSUE TITLE
Saved search is not working correctly

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#853] opened 2016-02-09 16:47 UTC

**Comment by aekhendry** [comment] 2016-02-09 16:50
I add a new saved search on hub, featuring two projects. I refresh and reset search page. I use my new saved search. Saved search is now only showing one of the two projects worth of compounds. This remains the case even if I change the project manually, even removing the project for which the data is showing. 

Hub Chrome

**Comment by PaulBarrett79** [comment] 2016-02-15 09:43
Duplicate of #896 - closing

**Closed** 2016-02-15 09:44 UTC
Labels: bug, priority: Showstopper
